
import { getGuildLanguage } from '../models/GuildModel.js';


export const translations = {
  en: {

    'error.generic': 'An error occurred while executing the command.',
    'error.title': 'Error',
    'error.permission': 'You do not have permission to use this command.',
    'error.guild_only': 'This command can only be used in a server.',
    'success': 'Success!',
    'loading': 'Loading...',
    'none': 'None',
    'unknown': 'Unknown',
    

    'language.title': 'Language Settings',
    'language.no_permission': 'You need "Manage Server" permission to change the bot language.',
    'language.already_set_en': 'Language is already set to English.',
    'language.already_set_ru': 'Language is already set to Russian.',
    'language.changed_en': 'Bot language has been changed to English for this server.',
    'language.changed_ru': 'Bot language has been changed to Russian for this server.',
    'language.error': 'An error occurred while changing the language.',
    

    'case.title': 'Cases',
    'case.your_cases': 'Your Cases',
    'case.have_cases': 'You have cases:',
    'case.no_cases': 'You don\'t have any cases yet.',
    'case.time_remaining': 'To get a case you need to spend more time in voice channels:',
    'case.no_cases_to_open': 'You don\'t have any cases to open.',
    'case.error_opening': 'Error opening the case!',
    'case.opened': 'Case opened!',
    'case.received': 'You received:',
    'case.open': 'Open',
    'case.open_again': 'Open Again',
    'case.cases_left': 'Cases left:',
    'case.only_user_can_open': 'Only the user who called the command can open the case!',
    'case.error_opening_case': 'An error occurred while opening the case.',
    

    'friendship.title': 'Friendship Collection',
    'friendship.grid_title': 'Friendship Collection Grid',
    'friendship.all_ponies': 'All Ponies',
    'friendship.owned_ponies': 'Owned Ponies',
    'friendship.missing_ponies': 'Missing Ponies',
    'friendship.basic_ponies': 'Basic Ponies',
    'friendship.rare_ponies': 'Rare Ponies',
    'friendship.epic_ponies': 'Epic Ponies',
    'friendship.mythic_ponies': 'Mythic Ponies',
    'friendship.legend_ponies': 'Legend Ponies',
    'friendship.custom_ponies': 'Custom Ponies',
    'friendship.secret_ponies': 'Secret Ponies',
    'friendship.event_ponies': 'Event Ponies',
    'friendship.unique_ponies': 'Unique Ponies',
    'friendship.column1': 'Column 1',
    'friendship.column2': 'Column 2',
    'friendship.previous': 'Previous',
    'friendship.next': 'Next',
    'friendship.filter': 'Filter',
    'friendship.detailed_view': 'Detailed View',
    'friendship.search': 'Search',
    'friendship.search_title': 'Search Ponies',
    'friendship.search_prompt': 'Enter pony name to search:',
    'friendship.search_results': 'Search Results',
    'friendship.collection': 'Collection',
    'friendship.filter_label': 'Filter',
    'friendship.grid': 'Grid',
    'friendship.ponies_owned': 'ponies owned',
    'friendship.shown': 'shown',
    'friendship.ponies': 'ponies',
    'friendship.owned_only': 'Owned only',
    'friendship.missing_only': 'Missing only',
    'friendship.all_ponies_filter': 'All ponies',
    'friendship.rarity': 'rarity',
    'friendship.add_to_favorites': 'Add to favorites',
    'friendship.remove_from_favorites': 'Remove from favorites',
    'friendship.no_results': 'No ponies found matching your search.',
    'friendship.back_to_grid': 'Back to Grid',
    'friendship.toggle_favorite': 'Toggle Favorite',
    'friendship.interaction_not_for_you': 'This interaction is not for you!',
    

    'currency.bits': 'bits',
    'currency.harmony': 'harmony',
    

    'inventory.your_inventory': 'Your Inventory',
    'inventory.building_resources': 'Building Resources',
    'inventory.magical_resources': 'Magical Resources', 
    'inventory.farm_resources': 'Farm Resources',
    'inventory.halloween_resources': 'Halloween Resources',
    'inventory.resource_stats': 'Resource Statistics',
    'inventory.total_wealth': 'Total Wealth',
    'inventory.tip': 'Use farm commands and events to earn resources',
    

    'economy.currency': 'Currency',
    

    'balance.title': 'Balance',
    'balance.your_balance': 'Your Balance',
    'balance.bits': 'Bits',
    'balance.cash': 'Cash',
    'balance.bank': 'Bank',
    'balance.harmony': 'Harmony',
    'balance.deposit': 'Deposit',
    'balance.withdraw': 'Withdraw',
    'balance.need_pony': 'You need to create a pony first! Use `/equestria` command.',
    'balance.button_access_denied': 'Only the pony who opened this bank account can use these buttons!',
    'balance.pony_not_found': 'Error: Pony not found!',
    'balance.select_deposit_amount': 'Select the amount you want to deposit into your bank account:',
    'balance.select_withdraw_amount': 'Select the amount you want to withdraw from your bank account:',
    'balance.cannot_move_zero': 'You cannot move 0 or negative bits!',
    'balance.insufficient_funds': 'Insufficient Funds',
    'balance.insufficient_cash': 'Insufficient cash: {current}/{required} bits',
    'balance.insufficient_bank': 'Insufficient bank balance: {current}/{required} bits',
    'balance.deposit_success': 'Successfully deposited {amount} bits into your bank account!',
    'balance.withdraw_success': 'Successfully withdrew {amount} bits from your bank account!',
    'balance.all': 'All',
    
    'crime.title': 'Crime',
    'crime.cooldown': 'You need to wait {hours} hours before committing another crime.',
    'crime.self_target': 'You cannot commit a crime against yourself!',
    'crime.same_target': 'You cannot target the same player twice in a row.',
    'crime.no_target_pony': 'Target player doesn\'t have a pony.',
    'crime.no_target_bits': '{target} has no bits! Find a richer target to steal from.',
    'crime.no_user_bits': 'You have no bits! If you get caught, you won\'t be able to pay the fine. Earn some bits first.',
    'crime.success': 'Successful Crime',
    'crime.failure': 'You Got Caught!',
    'crime.earned': 'You earned {amount} bits',
    'crime.lost': 'You lost {amount} bits',
    'crime.success_messages': [
      'You snuck into {target}\'s house and stole {amount} bits!',
      'You quietly took {amount} bits from {target}\'s bag!',
      'While {target} was distracted, you managed to steal {amount} bits!',
      'You committed a daring robbery and stole {amount} bits from {target}!',
      'Under the cover of night, you broke into {target}\'s vault and took {amount} bits!',
      'You switched the bill at the restaurant and tricked {target} out of {amount} bits!',
      'Disguised as a tax collector, you swindled {amount} bits from {target}!'
    ],
    'crime.fail_messages': [
      'You were caught by the Royal Guard while trying to rob {target}! You lost {amount} bits as a fine.',
      'You tripped over {target}\'s tail during the theft and got caught! Lost {amount} bits.',
      'Princess Celestia personally caught you in the act! You had to give up {amount} bits.',
      'Your theft attempt was noticed by Twilight and her friends. You lost {amount} bits.',
      'Rainbow Dash was too fast and caught you red-hoofed! You lost {amount} bits.',
      'Pinkie Pie predicted your theft attempt and set a trap! Lost {amount} bits.',
      'Applejack noticed your dishonesty and reported you to the guard. You lost {amount} bits.'
    ],
    
    'equestria.title': 'Welcome to Equestria!',
    'equestria.no_pony_title': '❌ No Pony Found',
    'equestria.no_pony_description': 'You need to create a pony before using this command!\n\nUse `/equestria` to create your own pony and start your adventure in Equestria.',
    'equestria.already_have_pony_title': 'You Already Have a Pony',
    'equestria.already_have_pony': 'You already have a pony named **{name}**. Use `/profile` to see your pony\'s details.',
    'equestria.already_have_pony_simple': 'You already have a pony. Use `/profile` to see your pony\'s details.',
    'equestria.create_pony_modal_title': 'Create Your Pony',
    'equestria.pony_name_label': 'Pony Name (max 30 characters)',
    'equestria.pony_name_placeholder': 'Enter your pony\'s name',
    'equestria.pony_age_label': 'Pony Age (1-1000 years)',
    'equestria.pony_age_placeholder': 'Enter your pony\'s age (1-1000)',
    'equestria.pony_race_label': 'Pony Race',
    'equestria.pony_race_placeholder': 'earth, unicorn, pegasus, alicorn, zebra, changeling, hippogriff, crystal, batpony, seapony',
    'equestria.pony_description_label': 'Pony Description (max 300 characters)',
    'equestria.pony_description_placeholder': 'Describe your pony',
    'equestria.invalid_age': 'Invalid age! Please enter a number between 1 and 1000.',
    'equestria.invalid_race': 'Invalid race! Available races: earth, unicorn, pegasus, alicorn, zebra, changeling, hippogriff, crystal, batpony, seapony.',
    'equestria.invalid_name': 'Invalid name! Name must be 1-30 characters long.',
    'equestria.invalid_description': 'Invalid description! Description must be less than 300 characters.',
    'equestria.pony_created': 'Congratulations! Your pony **{name}** has been created successfully!',
    'equestria.creation_failed': 'Failed to create pony. Please try again.',
    
    'mypony.user_no_pony': '{username} doesn\'t have a pony yet!',
    
    'leaders.title_bits': 'Top Leaders - Bits',
    'leaders.title_level': 'Top Leaders - Level',
    'leaders.title_voice': 'Top Leaders - Voice Activity',
    'leaders.title_ponies': 'Top Leaders - Collected Ponies',
    'leaders.desc_bits': 'Wealthiest users globally',
    'leaders.desc_level': 'Highest level users on this server',
    'leaders.desc_voice': 'Most active voice users globally',
    'leaders.desc_ponies': 'Users with most collected ponies globally',
    'leaders.no_data': 'No data available for this category yet!\n\nYou are not ranked in this category yet!',
    'leaders.invalid_page': 'Invalid Page',
    'leaders.invalid_page_desc': 'There are only {total} pages available!\n\nChoose a page between 1 and {total}.',
    'leaders.position': 'Position',
    'leaders.user': 'User',
    'leaders.level': 'Level',
    'leaders.rating': 'Rating',
    'leaders.voice_time': 'Voice Time',
    'leaders.pony_count': 'Ponies',
    'leaders.total_bits': 'Total Bits',
    'leaders.button_bits': 'Bits',
    'leaders.button_level': 'Level',
    'leaders.button_voice': 'Voice',
    'leaders.button_ponies': 'Ponies',
    'leaders.page_info': 'Page {current} of {total}',
    'leaders.previous': 'Previous',
    'leaders.next': 'Next',
    
    'mareslut.title': 'Mare Services',
    'mareslut.self_target': 'You cannot offer your services to yourself! That\'s just... weird.',
    'mareslut.cooldown': 'You need to rest after your last mare service! Wait {hours}h {minutes}m {seconds}s before offering services again.',
    'mareslut.success': 'Service Successful!',
    'mareslut.failed': 'Service Failed!',
    'mareslut.moral_damage': 'Moral Damage!',
    'mareslut.insufficient_bits_title': 'Insufficient Bits',
    'mareslut.insufficient_bits_description': 'You have no bits! If your services are rejected, you won\'t be able to cover your expenses. Earn some bits first.',
    'mareslut.no_target_pony': '{target} doesn\'t have a pony! You can\'t offer your services to someone who isn\'t part of Equestria.',
    'mareslut.no_payment_possible_title': 'No Payment Possible',
    'mareslut.no_payment_possible_description': '{target} has no bits! Find a richer client who can afford your services.',
    

    'mareslut.success_1': 'You offered your "special services" to {target} and earned {amount} bits for your performance!',
    'mareslut.success_2': 'You showed {target} your best mare tricks and received {amount} bits as payment!',
    'mareslut.success_3': '{target} was impressed by your flank-shaking skills and paid you {amount} bits!',
    'mareslut.success_4': 'Your seductive wink convinced {target} to give you {amount} bits for a private show!',
    'mareslut.success_5': 'You danced around the pole like a professional mare and earned {amount} bits from {target}!',
    'mareslut.success_6': 'Your charming personality and mare skills earned you {amount} bits from {target}!',
    'mareslut.success_7': '{target} couldn\'t resist your mare charm and paid {amount} bits for your company!',
    

    'mareslut.fail_1': '{target} wasn\'t impressed by your mare services and refused to pay you. You lost {amount} bits trying to impress them!',
    'mareslut.fail_2': 'Your flank-shaking technique needs work! {target} demanded a refund and you lost {amount} bits.',
    'mareslut.fail_3': 'You tried to seduce {target}, but they reported you to the Royal Guard! You were fined {amount} bits.',
    'mareslut.fail_4': 'Your mare services were so bad that {target} complained to Princess Celestia. You lost {amount} bits in reputation damage!',
    'mareslut.fail_5': 'You tried to overcharge {target} for your mare services and got caught! You had to pay {amount} bits in compensation.',
    'mareslut.fail_6': 'Your mare performance was so awkward that {target} left without paying. You lost {amount} bits on preparation costs!',
    'mareslut.fail_7': 'The Health Inspector caught you offering unauthorized mare services and fined you {amount} bits!',
    

    'mareslut.moral_1': 'You forgot about safety precautions during your mare services and had to spend {amount} bits on medical treatment!',
    'mareslut.moral_2': 'Your enthusiastic performance resulted in a pulled muscle! Recovery cost you {amount} bits.',
    'mareslut.moral_3': 'You slipped during your pole dance and had to visit the local hospital. Medical bills: {amount} bits.',
    'mareslut.moral_4': 'Your reputation in town suffered after your mare services went wrong. PR recovery cost: {amount} bits.',
    'mareslut.moral_5': 'You caught a cold while working as a mare for hire in the rain. Medicine cost: {amount} bits.',
    'mareslut.moral_6': 'Your mare costume got damaged during the performance. Repair costs: {amount} bits.',
    'mareslut.moral_7': 'Princess Twilight gave you a lecture about proper mare behavior. Mandatory educational materials cost you {amount} bits.',
    

    'mareslut.bits_added': '+{amount} bits added to your balance!',
    'mareslut.bits_deducted': '-{amount} bits deducted from your balance.',
    'mareslut.harmony_lost_success': '-10 <:harmony:1416514347789844541>',
    'mareslut.harmony_lost_fail': '-5 <:harmony:1416514347789844541>',
    'mareslut.additional_expenses': '-{amount} bits in additional expenses.',
    
    'mypony.title': 'My Pony',
    'mypony.your_pony': 'Your Pony',
    'mypony.no_pony': 'You don\'t have a pony yet.',
    
    'protection.title': 'Protection',
    'protection.error_retrieve': 'Could not retrieve protection information.',
    'protection.remaining_time': 'Your protection is **active** for {time} more.',
    'protection.activated': 'Protection activated for 24 hours! Your ponies are now safe from theft.',
    'protection.already_protected': 'You are already protected from pony theft.',
    
    'quests.title': 'Quests',
    'quests.available': 'Available Quests',
    'quests.completed': 'Completed Quests',
    'quests.no_quests': 'No quests available.',
    
    'timely.title': 'Daily Fortune',
    'timely.cooldown': 'you have already opened a cookie recently!\nYou will be able to open the next one only in',
    'timely.hours': 'hours',
    'timely.reward_footer': 'Come back in {cooldown} hours',
    'timely.error': 'An error occurred while getting your fortune. Please try again later.',
    
    'trade.title': 'Trade',
    'trade.proposal': 'Trade Proposal',
    'trade.accept': 'Accept',
    'trade.decline': 'Decline',
    'trade.completed': 'Trade completed!',
    'trade.cancelled': 'Trade cancelled!',
    
    'transfer_bits.title': 'Transfer Bits',
    'transfer_bits.success': 'Bits transferred successfully!',
    'transfer_bits.insufficient': 'Insufficient bits.',
    'transfer_bits.invalid_amount': 'Invalid amount.',
    'transfer_bits.transferred': 'Transferred',
    'transfer_bits.to': 'to',
    
    'venture.title': 'Venture',
    'venture.success': 'Venture successful!',
    'venture.failed': 'Venture failed!',
    'venture.cooldown': 'You need to wait before starting another venture.',
    'venture.reward': 'You earned',
    'venture.cooldown_title': 'Cooldown',
    'venture.cooldown_message': '> 🍪 Time to eat a cookie while you\'re waiting for your next adventure!\n> Please wait `{minutes}m {seconds}s` before venturing out again.',
    'venture.encountered_pony': '> While exploring Equestria, you encountered a pony{unique}.\n\n> **Rarity:** {rarity}\n> **Name:** `{name}`',
    'venture.unique': ' (Unique!)',
    'venture.not_for_you': 'This interaction is not for you!',
    'venture.not_enough_bits': '❌ Not enough bits',
    'venture.super_hint_cost': 'To use "Super Hint" you need 750 bits. You have: {bits} bits.',
    'venture.adventure_continues': 'Adventure Continues',
    'venture.rewards': '> {message}\n\n> **Rewards:**\n> <:bits:1411354539935666197> **{bits} bits**\n> {resource_emoji} **{resource_amount} {resource_type}**',
    'venture.enter_name': 'Who is this pony? Enter their name:',
    'venture.correct_answer': '> Excellent! You correctly identified **{name}**!\n *{description}*\n\n> **Rarity:** {rarity}\n> **<:bits:1411354539935666197> +{bits_reward} bits**{resource_text}{duplicate_text}{faction_points_text}\n> {friend_text}',
    'venture.default_description': 'A wonderful pony to have as a friend!',
    

    'venture.befriend': 'Befriend',
    'venture.ignore': 'Ignore',
    'venture.hint': 'Hint',
    'venture.super_hint': 'Super Hint',
    

    'venture.title_basic_1': 'A pony appears!',
    'venture.title_basic_2': 'You found a pony!',
    'venture.title_basic_3': 'A friendly pony approaches!',
    'venture.title_basic_4': 'Look who\'s here!',
    'venture.title_rare_1': 'Ooh, a rare pony!',
    'venture.title_rare_2': 'What a rare find!',
    'venture.title_rare_3': 'A rare pony emerges!',
    'venture.title_rare_4': 'How rare and wonderful!',
    'venture.title_epic_1': 'EPIC discovery ahead!',
    'venture.title_epic_2': 'An EPIC pony appears!',
    'venture.title_epic_3': 'This is getting EPIC!',
    'venture.title_epic_4': 'EPIC pony encounter!',
    'venture.title_mythic_1': 'WOW! A mythical pony is here!',
    'venture.title_mythic_2': 'MYTHICAL creature spotted!',
    'venture.title_mythic_3': 'Legends come to life!',
    'venture.title_mythic_4': 'A MYTHIC encounter awaits!',
    'venture.title_legend_1': 'NO WAY! IT\'S A LEGEND!',
    'venture.title_legend_2': 'LEGENDARY pony found!',
    'venture.title_legend_3': 'THIS IS LEGENDARY!',
    'venture.title_legend_4': 'A LEGEND walks among us!',
    'venture.title_custom_1': 'Something CUSTOM this way comes!',
    'venture.title_custom_2': 'A CUSTOM pony appears!',
    'venture.title_custom_3': 'UNIQUE and CUSTOM!',
    'venture.title_custom_4': 'Custom-made magic!',
    'venture.title_secret_1': 'Shh... it\'s a SECRET!',
    'venture.title_secret_2': 'SECRET pony discovered!',
    'venture.title_secret_3': 'The SECRET is revealed!',
    'venture.title_secret_4': 'A hidden SECRET appears!',
    'venture.title_event_1': 'SPECIAL EVENT encounter!',
    'venture.title_event_2': 'Something EXTRAORDINARY appears!',
    'venture.title_event_3': 'LEGENDARY EVENT pony!',
    'venture.title_event_4': 'Once-in-a-lifetime EVENT!',
    

    'venture.timeout': 'Time\'s up! The pony ran away.',
    'venture.wrong_guess': 'That\'s not right. Take another guess!',
    'venture.already_have': 'You already have this pony in your collection!',
    'venture.added_to_collection': 'Added to your collection!',
    'venture.duplicate_bonus': '\n> <:bits:1411354539935666197> **+{amount} bits** (duplicate bonus)',
    'venture.faction_points': '\n> ⚔️ **+{amount} {faction} faction points**',
    'venture.resource_reward': '\n> {emoji} **+{amount} {type}**',
    'venture.interaction_ended': 'Interaction ended.',
    'venture.hint_revealed': 'Letter revealed: **{letter}**',
    'venture.super_hint_revealed': 'Super hint: **{hint}**',
    'venture.guess_instruction': 'Guess the pony name in English!',
    

    'validator.command_error': 'Something went wrong. Please try again.',
    'validator.permission_error': 'I can\'t do that! I need special permission to touch those gears!',
    'validator.user_input_error': 'That doesn\'t look right to my dental expertise! Could you check again?',
    'validator.missing_args': 'I need more information to help with your teeth... I mean, with your request!',
    'validator.api_error': 'The time stream is disrupted! I can\'t connect to the necessary dimensions right now!',
    'validator.database_error': 'My dental records got mixed up! Give me a moment to reorganize!',
    'validator.cooldown_error': 'Whoa there! My pocket watch needs to cool down before we do that again!',
    'validator.user_not_found': 'Oh my! I can\'t find that pony in this server!',
    'validator.cannot_moderate': 'I can\'t moderate this pony! Their role is higher than mine or they have special permissions!',
    'validator.self_moderate': 'Oh dear! You can\'t moderate yourself! That would be like me trying to fix my own teeth!',
    'validator.bot_moderate': '*giggles* I can\'t moderate myself, silly! Who would help with dental appointments then?',
    'validator.not_timed_out': 'This pony isn\'t in timeout! Their teeth are already free to chatter!',
    'validator.already_banned': 'This pony is already banned from the server! Their teeth are long gone!',
    'validator.not_original_user': 'Oh my! Your hooves aren\'t worthy of adjusting these delicate gears! Only the pony who started this can touch these controls!',
    'validator.nsfw_content': 'Oh my! *blushes* I can only show those kinds of images in NSFW channels! My dental ethics won\'t allow it otherwise!',
    'validator.nsfw_channel_required': 'Oh my! *blushes* This command can only be used in NSFW channels! My dental ethics won\'t allow it otherwise!',
    

    'setup.welcome': 'I\'m excited to help you set up your server for success! As a time management expert, I know how important it is to have everything organized properly. Let me help you make your server safe and tidy!',
    'setup.everyone_checks_title': 'Everyone/Here Mention Permissions Check',
    'setup.everyone_checks_description': 'I\'ll check if any roles have the permission to mention everyone or here, which can be disruptive for large servers.',
    'setup.everyone_checks_loading': 'Checking mention permissions for all roles... this might take a moment!',
    'setup.everyone_checks_success': 'I\'ve successfully checked all roles for mention permissions!',
    'setup.everyone_checks_no_issues': 'Great news! No roles with risky mention permissions were found. Your server is already safe from unwanted mass pings!',
    'setup.everyone_checks_fixed': 'I\'ve successfully removed the mention everyone/here permission from the problematic roles.',
    'setup.everyone_checks_cant_fix': 'I don\'t have enough permissions to fix these roles. Please give me \'Manage Roles\' permission and try again.',
    'setup.permission_checks_title': 'Role Permissions Audit',
    'setup.permission_checks_description': 'I\'ll analyze all roles and their permissions to help you identify potential security risks.',
    'setup.permission_checks_loading': 'Analyzing role permissions... this might take a moment!',
    'setup.permission_checks_success': 'I\'ve successfully audited all role permissions!',
    'setup.permission_checks_safe': 'This role has appropriate permissions for its purpose.',
    'setup.permission_checks_summary': 'Here\'s a summary of your server\'s roles and permissions:',
    

    'help.title': 'Command Help',
    'help.description': 'Available commands: **{total}**\nSelect a category below:',
    'help.commands_count': '{count} commands',
    'help.category_utility': 'Utility',
    'help.category_economy': 'Economy',
    'help.category_moderation': 'Moderation',
    'help.category_management': 'Management',
    'help.buttons_not_for_you': 'Only the command user can use these buttons!',
    'help.category_title': '{category} Commands',
    'help.back_to_menu': 'Back to Menu',
    

    'rarity.BASIC': 'Basic',
    'rarity.RARE': 'Rare', 
    'rarity.EPIC': 'Epic',
    'rarity.MYTHIC': 'Mythic',
    'rarity.LEGEND': 'Legend',
    'rarity.CUSTOM': 'Custom',
    'rarity.SECRET': 'Secret',
    'rarity.EVENT': 'Event',
    'rarity.UNIQUE': 'Unique',
    'rarity.EXCLUSIVE': 'Exclusive'
  },
  
  ru: {

    'error.generic': 'Произошла ошибка при выполнении команды.',
    'error.title': 'Ошибка',
    'error.permission': 'У вас нет прав для использования этой команды.',
    'error.guild_only': 'Эту команду можно использовать только на сервере.',
    'success': 'Успешно!',
    'loading': 'Загрузка...',
    'none': 'Нет',
    'unknown': 'Неизвестно',
    

    'language.title': 'Настройки языка',
    'language.no_permission': 'Вам нужны права "Управление сервером" для смены языка бота.',
    'language.already_set_en': 'Язык уже установлен на английский.',
    'language.already_set_ru': 'Язык уже установлен на русский.',
    'language.changed_en': 'Язык бота изменен на английский для этого сервера.',
    'language.changed_ru': 'Язык бота изменен на русский для этого сервера.',
    'language.error': 'Произошла ошибка при смене языка.',
    

    'case.title': 'Кейсы',
    'case.your_cases': 'Ваши кейсы',
    'case.have_cases': 'У вас есть кейсы:',
    'case.no_cases': 'У вас пока нет кейсов.',
    'case.time_remaining': 'Чтобы получить кейс, нужно провести больше времени в голосовых каналах:',
    'case.no_cases_to_open': 'У вас нет кейсов для открытия.',
    'case.error_opening': 'Ошибка при открытии кейса!',
    'case.opened': 'Кейс открыт!',
    'case.received': 'Вы получили:',
    'case.open': 'Открыть',
    'case.open_again': 'Открыть еще',
    'case.cases_left': 'Осталось кейсов:',
    'case.only_user_can_open': 'Только пользователь, вызвавший команду, может открыть кейс!',
    'case.error_opening_case': 'Произошла ошибка при открытии кейса.',
    

    'friendship.title': 'Коллекция дружбы',
    'friendship.grid_title': 'Сетка коллекции дружбы',
    'friendship.all_ponies': 'Все пони',
    'friendship.owned_ponies': 'Имеющиеся пони',
    'friendship.missing_ponies': 'Отсутствующие пони',
    'friendship.basic_ponies': 'Базовые пони',
    'friendship.rare_ponies': 'Редкие пони',
    'friendship.epic_ponies': 'Эпические пони',
    'friendship.mythic_ponies': 'Мифические пони',
    'friendship.legend_ponies': 'Легендарные пони',
    'friendship.custom_ponies': 'Кастомные пони',
    'friendship.secret_ponies': 'Секретные пони',
    'friendship.event_ponies': 'Ивентовые пони',
    'friendship.unique_ponies': 'Уникальные пони',
    'friendship.column1': 'Столбец 1',
    'friendship.column2': 'Столбец 2',
    'friendship.previous': 'Назад',
    'friendship.next': 'Вперед',
    'friendship.filter': 'Фильтр',
    'friendship.detailed_view': 'Детальный вид',
    'friendship.search': 'Поиск',
    'friendship.search_title': 'Поиск пони',
    'friendship.search_prompt': 'Введите имя пони для поиска:',
    'friendship.search_results': 'Результаты поиска',
    'friendship.no_results': 'Не найдено пони, соответствующих вашему поиску.',
    'friendship.back_to_grid': 'Назад к сетке',
    'friendship.toggle_favorite': 'Переключить избранное',
    'friendship.interaction_not_for_you': 'Это взаимодействие не для вас!',
    'friendship.collection': 'Коллекция',
    'friendship.filter_label': 'Фильтр',
    'friendship.grid': 'Сетка',
    'friendship.ponies_owned': 'пони получено',
    'friendship.shown': 'показано',
    'friendship.ponies': 'пони',
    'friendship.owned_only': 'Только имеющиеся',
    'friendship.missing_only': 'Только отсутствующие',
    'friendship.all_ponies_filter': 'Все пони',
    'friendship.rarity': 'редкость',
    'friendship.add_to_favorites': 'Добавить в избранное',
    'friendship.remove_from_favorites': 'Убрать из избранного',
    

    'currency.bits': 'битсы',
    'currency.harmony': 'гармония',
    

    'inventory.your_inventory': 'Ваш инвентарь',
    'inventory.building_resources': 'Строительные ресурсы',
    'inventory.magical_resources': 'Магические ресурсы',
    'inventory.farm_resources': 'Фермерские ресурсы', 
    'inventory.halloween_resources': 'Хеллоуинские ресурсы',
    'inventory.resource_stats': 'Статистика ресурсов',
    'inventory.total_wealth': 'Общее богатство',
    'inventory.tip': 'Используйте фермерские команды и события для получения ресурсов',
    

    'economy.currency': 'Валюта',
    

    'balance.title': 'Баланс',
    'balance.your_balance': 'Ваш баланс',
    'balance.bits': 'Битсы',
    'balance.cash': 'Наличные',
    'balance.bank': 'Банк',
    'balance.harmony': 'Гармония',
    'balance.deposit': 'Вложить',
    'balance.withdraw': 'Снять',
    'balance.need_pony': 'Сначала нужно создать пони! Используйте команду `/equestria`.',
    'balance.button_access_denied': 'Только пони, открывший этот банковский счет, может использовать эти кнопки!',
    'balance.pony_not_found': 'Ошибка: Пони не найден!',
    'balance.select_deposit_amount': 'Выберите сумму, которую хотите вложить в банковский счет:',
    'balance.select_withdraw_amount': 'Выберите сумму, которую хотите снять с банковского счета:',
    'balance.cannot_move_zero': 'Нельзя перемещать 0 или отрицательное количество битсов!',
    'balance.insufficient_funds': 'Недостаточно средств',
    'balance.insufficient_cash': 'Недостаточно наличных: {current}/{required} битсов',
    'balance.insufficient_bank': 'Недостаточно средств в банке: {current}/{required} битсов',
    'balance.deposit_success': 'Успешно вложено {amount} битсов в банковский счет!',
    'balance.withdraw_success': 'Успешно снято {amount} битсов с банковского счета!',
    'balance.all': 'Все',
    
    'crime.title': 'Преступление',
    'crime.cooldown': 'Нужно подождать {hours} часов перед следующим преступлением.',
    'crime.self_target': 'Вы не можете совершить преступление против себя!',
    'crime.same_target': 'Вы не можете выбирать одного и того же игрока дважды подряд.',
    'crime.no_target_pony': 'У целевого участника нет пони.',
    'crime.no_target_bits': 'У {target} нет битсов! Найдите более богатую цель для кражи.',
    'crime.no_user_bits': 'У вас нет битсов! Если вас поймают, вы не сможете заплатить штраф. Сначала заработайте бисты.',
    'crime.success': 'Успешное преступление',
    'crime.failure': 'Вас поймали!',
    'crime.earned': 'Вы заработали {amount} битсов',
    'crime.lost': 'Вы потеряли {amount} битсов',
    'crime.success_messages': [
      'Вы прокрались в дом {target} и украли {amount} битсов!',
      'Вы тихо взяли {amount} битсов из сумки {target}!',
      'Пока {target} отвлекался, вам удалось украсть {amount} битсов!',
      'Вы совершили дерзкое ограбление и украли {amount} битсов у {target}!',
      'Под покровом ночи вы проникли в хранилище {target} и взяли {amount} битсов!',
      'Вы подменили счет в ресторане и обманули {target} на {amount} битсов!',
      'Переодевшись налоговым инспектором, вы выманили {amount} битсов у {target}!'
    ],
    'crime.fail_messages': [
      'Вас поймала Королевская стража при попытке ограбить {target}! Вы потеряли {amount} битсов в качестве штрафа.',
      'Вы споткнулись о хвост {target} во время кражи и попались! Потеряли {amount} битсов.',
      'Принцесса Селестия лично поймала вас на месте преступления! Пришлось отдать {amount} битсов.',
      'Ваша попытка кражи была замечена Твайлайт и её друзьями. Вы потеряли {amount} битсов.',
      'Рэйнбоу Дэш была слишком быстрой и поймала вас с поличным! Вы потеряли {amount} битсов.',
      'Пинки Пай предсказала вашу попытку кражи и поставила ловушку! Потеряли {amount} битсов.',
      'Эпплджек заметила вашу нечестность и сообщила страже. Вы потеряли {amount} битсов.'
    ],
    
    'equestria.title': 'Добро пожаловать в Эквестрию!',
    'equestria.no_pony_title': '❌ Пони не найден',
    'equestria.no_pony_description': 'Вам нужно создать пони перед использованием этой команды!\n\nИспользуйте `/equestria` чтобы создать своего пони и начать приключение в Эквестрии.',
    'equestria.already_have_pony_title': 'У вас уже есть пони',
    'equestria.already_have_pony': 'У вас уже есть пони по имени **{name}**. Используйте `/profile` чтобы посмотреть детали вашего пони.',
    'equestria.already_have_pony_simple': 'У вас уже есть пони. Используйте `/profile` чтобы посмотреть детали вашего пони.',
    'equestria.create_pony_modal_title': 'Создайте своего пони',
    'equestria.pony_name_label': 'Имя пони (макс. 30 символов)',
    'equestria.pony_name_placeholder': 'Введите имя вашего пони',
    'equestria.pony_age_label': 'Возраст пони (1-1000 лет)',
    'equestria.pony_age_placeholder': 'Введите возраст вашего пони (1-1000)',
    'equestria.pony_race_label': 'Раса пони',
    'equestria.pony_race_placeholder': 'earth, unicorn, pegasus, alicorn, zebra, changeling, hippogriff, crystal, batpony, seapony',
    'equestria.pony_description_label': 'Описание пони (макс. 300 символов)',
    'equestria.pony_description_placeholder': 'Опишите вашего пони',
    'equestria.invalid_age': 'Неверный возраст! Введите число от 1 до 1000.',
    'equestria.invalid_race': 'Неверная раса! Доступные расы: earth, unicorn, pegasus, alicorn, zebra, changeling, hippogriff, crystal, batpony, seapony.',
    'equestria.invalid_name': 'Неверное имя! Имя должно быть от 1 до 30 символов.',
    'equestria.invalid_description': 'Неверное описание! Описание должно быть менее 300 символов.',
    'equestria.pony_created': 'Поздравляем! Ваш пони **{name}** был/а успешно создан!',
    'equestria.creation_failed': 'Не удалось создать пони. Попробуйте снова.',
    
    'mypony.user_no_pony': 'У {username} еще нет пони!',
    
    'leaders.title_bits': 'Топ лидеры - Битсы',
    'leaders.title_level': 'Топ лидеры - Уровень',
    'leaders.title_voice': 'Топ лидеры - Голосовая активность',
    'leaders.title_ponies': 'Топ лидеры - Собранные пони',
    'leaders.desc_bits': 'Самые богатые пользователи глобально',
    'leaders.desc_level': 'Пользователи с высшим уровнем на этом сервере',
    'leaders.desc_voice': 'Самые активные пользователи в голосовых каналах глобально',
    'leaders.desc_ponies': 'Пользователи с наибольшим количеством собранных пони глобально',
    'leaders.no_data': 'Пока нет данных для этой категории!\n\nВы еще не ранжированы в этой категории!',
    'leaders.invalid_page': 'Неверная страница',
    'leaders.invalid_page_desc': 'Доступно только {total} страниц!\n\nВыберите страницу от 1 до {total}.',
    'leaders.position': 'Позиция',
    'leaders.user': 'Пользователь',
    'leaders.level': 'Уровень',
    'leaders.rating': 'Рейтинг',
    'leaders.voice_time': 'Время в голосе',
    'leaders.pony_count': 'Пони',
    'leaders.total_bits': 'Всего битсов',
    'leaders.button_bits': 'Битсы',
    'leaders.button_level': 'Уровень',
    'leaders.button_voice': 'Голос',
    'leaders.button_ponies': 'Пони',
    'leaders.page_info': 'Страница {current} из {total}',
    'leaders.previous': 'Назад',
    'leaders.next': 'Вперед',
    
    'mareslut.title': 'Кобыльи услуги',
    'mareslut.self_target': 'Вы не можете предложить услуги самому себе! Это просто... странно.',
    'mareslut.cooldown': 'Вам нужно отдохнуть после последней кобыльей услуги! Подождите {hours}ч {minutes}м {seconds}с перед следующим предложением услуг.',
    'mareslut.success': 'Услуга успешна!',
    'mareslut.failed': 'Услуга провалилась!',
    'mareslut.moral_damage': 'Моральный ущерб!',
    'mareslut.insufficient_bits_title': 'Недостаточно битсов',
    'mareslut.insufficient_bits_description': 'У вас нет битсов! Если ваши услуги будут отклонены, вы не сможете покрыть расходы. Сначала заработайте битсы.',
    'mareslut.no_target_pony': '{target} не имеет пони! Вы не можете предложить услуги тому, кто не является частью Эквестрии.',
    'mareslut.no_payment_possible_title': 'Оплата невозможна',
    'mareslut.no_payment_possible_description': 'У {target} нет битсов! Найдите более богатого клиента, который может позволить себе ваши услуги.',
    

    'mareslut.success_1': 'Вы предложили свои "особые услуги" {target} и заработали {amount} битсов за своё выступление!',
    'mareslut.success_2': 'Вы показали {target} свои лучшие кобыльи трюки и получили {amount} битсов в качестве оплаты!',
    'mareslut.success_3': '{target} был впечатлен вашими навыками тряски крупом и заплатил вам {amount} битсов!',
    'mareslut.success_4': 'Ваш соблазнительный подмигивание убедило {target} дать вам {amount} битсов за приватное шоу!',
    'mareslut.success_5': 'Вы танцевали вокруг шеста как профессиональная кобылка и заработали {amount} битсов от {target}!',
    'mareslut.success_6': 'Ваша обаятельная личность и кобыльи навыки принесли вам {amount} битсов от {target}!',
    'mareslut.success_7': '{target} не смог устоять перед вашим кобыльим обаянием и заплатил {amount} битсов за ваше общество!',
    

    'mareslut.fail_1': '{target} не впечатлился вашими кобыльими услугами и отказался платить. Вы потеряли {amount} битсов, пытаясь произвести впечатление!',
    'mareslut.fail_2': 'Ваша техника тряски крупом нуждается в доработке! {target} потребовал возврат денег, и вы потеряли {amount} битсов.',
    'mareslut.fail_3': 'Вы пытались соблазнить {target}, но они сообщили о вас Королевской страже! Вас оштрафовали на {amount} битсов.',
    'mareslut.fail_4': 'Ваши кобыльи услуги были настолько плохи, что {target} пожаловался Принцессе Селестии. Вы потеряли {amount} битсов из-за ущерба репутации!',
    'mareslut.fail_5': 'Вы пытались завысить цену для {target} за свои кобыльи услуги и попались! Вам пришлось заплатить {amount} битсов в качестве компенсации.',
    'mareslut.fail_6': 'Ваше кобылье выступление было настолько неловким, что {target} ушел, не заплатив. Вы потеряли {amount} битсов на расходах на подготовку!',
    'mareslut.fail_7': 'Инспектор здравоохранения Понивилля поймал вас на предложении несанкционированных кобыльих услуг и оштрафовал вас на {amount} битсов!',
    

    'mareslut.moral_1': 'Вы забыли о мерах предосторожности во время ваших кобыльих услуг и вам пришлось потратить {amount} битсов на медицинское лечение!',
    'mareslut.moral_2': 'Ваше чрезмерно энтузиастичное выступление привело к растяжению мышцы! Восстановление стоило вам {amount} битсов.',
    'mareslut.moral_3': 'Вы поскользнулись во время танца на шесте и вам пришлось посетить больницу Понивилля. Медицинские счета: {amount} битсов.',
    'mareslut.moral_4': 'Ваша репутация в Понивилле пострадала после того, как ваши кобыльи услуги пошли не так. Восстановление PR: {amount} битсов.',
    'mareslut.moral_5': 'Вы простудились, работая кобылкой по найму под дождем. Стоимость лекарств: {amount} битсов.',
    'mareslut.moral_6': 'Ваш кобылий костюм был поврежден во время выступления. Стоимость ремонта: {amount} битсов.',
    'mareslut.moral_7': 'Принцесса Твайлайт прочитала вам лекцию о правильном кобыльем поведении. Обязательные образовательные материалы стоили вам {amount} битсов.',
    

    'mareslut.bits_added': '+{amount} битсов добавлено на ваш баланс!',
    'mareslut.bits_deducted': '-{amount} битсов списано с вашего баланса.',
    'mareslut.harmony_lost_success': '-10 гармония',
    'mareslut.harmony_lost_fail': '-5 гармония',
    'mareslut.additional_expenses': '-{amount} битсов в дополнительных расходах.',
    
    'mypony.title': 'Моя пони',
    'mypony.your_pony': 'Ваша пони',
    'mypony.no_pony': 'У вас пока нет пони.',
    
    'protection.title': 'Защита',
    'protection.error_retrieve': 'Не удалось получить информацию о защите.',
    'protection.remaining_time': 'Ваша защита **активна** еще {time}.',
    'protection.activated': 'Защита активирована на 24 часа! Ваши пони теперь в безопасности от кражи.',
    'protection.already_protected': 'Вы уже защищены от кражи пони.',
    
    'quests.title': 'Квесты',
    'quests.available': 'Доступные квесты',
    'quests.completed': 'Выполненные квесты',
    'quests.no_quests': 'Нет доступных квестов.',
    
    'timely.title': 'Ежедневное предсказание',
    'timely.cooldown': 'вы уже открывали печенье недавно!\nСледующее сможете открыть только через',
    'timely.hours': 'часов',
    'timely.reward_footer': 'Вы получили {amount} битсов | Возвращайтесь через {cooldown} часов',
    'timely.error': 'Произошла ошибка при получении предсказания. Попробуйте позже.',
    
    'trade.title': 'Торговля',
    'trade.proposal': 'Предложение торговли',
    'trade.accept': 'Принять',
    'trade.decline': 'Отклонить',
    'trade.completed': 'Торговля завершена!',
    'trade.cancelled': 'Торговля отменена!',
    
    'transfer_bits.title': 'Перевод битсов',
    'transfer_bits.success': 'Битсы успешно переведены!',
    'transfer_bits.insufficient': 'Недостаточно битсов.',
    'transfer_bits.invalid_amount': 'Неверная сумма.',
    'transfer_bits.transferred': 'Переведено',
    'transfer_bits.to': 'пользователю',
    
    'venture.title': 'Предприятие',
    'venture.success': 'Предприятие успешно!',
    'venture.failed': 'Предприятие провалилось!',
    'venture.cooldown': 'Нужно подождать перед следующим предприятием.',
    'venture.reward': 'Вы заработали',
    'venture.cooldown_title': 'Откат',
    'venture.cooldown_message': '> Вы все еще отдыхаете после последнего приключения!\n> Пожалуйста, подождите `{minutes}м {seconds}с` перед следующим путешествием.',
    'venture.encountered_pony': '> Исследуя Эквестрию, вы встретили пони{unique}.\n\n> **Редкость:** {rarity}\n> **Имя:** `{name}`',
    'venture.unique': ' (Уникальный!)',
    'venture.not_for_you': 'Это взаимодействие не для вас!',
    'venture.not_enough_bits': '❌ Недостаточно битсов',
    'venture.super_hint_cost': 'Для использования "Супер подсказки" нужно 750 битсов. У вас: {bits} битсов.',
    'venture.adventure_continues': 'Приключение продолжается',
    'venture.rewards': '> {message}\n\n> **Награды:**\n> <:bits:1411354539935666197> **{bits} битсов**\n> {resource_emoji} **{resource_amount} {resource_type}**',
    'venture.enter_name': 'Кто этот пони? Введите его имя:',
    'venture.correct_answer': '> Отлично! Вы правильно определили **{name}**!\n *{description}*\n\n> **Редкость:** {rarity}\n> **<:bits:1411354539935666197> +{bits_reward} битсов**{resource_text}{duplicate_text}{faction_points_text}\n> {friend_text}',
    'venture.default_description': 'Замечательный пони, который может стать хорошим другом!',
    

    'venture.befriend': 'Подружиться',
    'venture.ignore': 'Игнорировать',
    'venture.hint': 'Подсказка',
    'venture.super_hint': 'Супер подсказка',
    

    'venture.title_basic_1': 'Появился пони!',
    'venture.title_basic_2': 'Вы нашли пони!',
    'venture.title_basic_3': 'Дружелюбный пони приближается!',
    'venture.title_basic_4': 'Посмотрите, кто здесь!',
    'venture.title_rare_1': 'О, редкий пони!',
    'venture.title_rare_2': 'Какая редкая находка!',
    'venture.title_rare_3': 'Появился редкий пони!',
    'venture.title_rare_4': 'Как редко и прекрасно!',
    'venture.title_epic_1': 'ЭПИЧЕСКОЕ открытие впереди!',
    'venture.title_epic_2': 'Появился ЭПИЧЕСКИЙ пони!',
    'venture.title_epic_3': 'Это становится ЭПИЧНО!',
    'venture.title_epic_4': 'ЭПИЧЕСКАЯ встреча с пони!',
    'venture.title_mythic_1': 'ВАУ! Здесь мифический пони!',
    'venture.title_mythic_2': 'МИФИЧЕСКОЕ существо замечено!',
    'venture.title_mythic_3': 'Легенды оживают!',
    'venture.title_mythic_4': 'Ждет МИФИЧЕСКАЯ встреча!',
    'venture.title_legend_1': 'НЕ МОЖЕТ БЫТЬ! ЭТО ЛЕГЕНДА!',
    'venture.title_legend_2': 'Найден ЛЕГЕНДАРНЫЙ пони!',
    'venture.title_legend_3': 'ЭТО ЛЕГЕНДАРНО!',
    'venture.title_legend_4': 'ЛЕГЕНДА ходит среди нас!',
    'venture.title_custom_1': 'Что-то ОСОБЕННОЕ приближается!',
    'venture.title_custom_2': 'Появился ОСОБЕННЫЙ пони!',
    'venture.title_custom_3': 'УНИКАЛЬНЫЙ и ОСОБЕННЫЙ!',
    'venture.title_custom_4': 'Созданная на заказ магия!',
    'venture.title_secret_1': 'Тш... это СЕКРЕТ!',
    'venture.title_secret_2': 'Обнаружен СЕКРЕТНЫЙ пони!',
    'venture.title_secret_3': 'СЕКРЕТ раскрыт!',
    'venture.title_secret_4': 'Появился скрытый СЕКРЕТ!',
    'venture.title_event_1': 'ОСОБАЯ ИВЕНТОВАЯ встреча!',
    'venture.title_event_2': 'Появляется что-то НЕВЕРОЯТНОЕ!',
    'venture.title_event_3': 'ЛЕГЕНДАРНЫЙ ИВЕНТОВЫЙ пони!',
    'venture.title_event_4': 'УНИКАЛЬНЫЙ ИВЕНТ раз в жизни!',
    

    'venture.timeout': 'Время вышло! Пони убежал.',
    'venture.wrong_guess': 'Это неправильно. Попробуйте еще раз!',
    'venture.already_have': 'У вас уже есть этот пони в коллекции!',
    'venture.added_to_collection': 'Добавлен в вашу коллекцию!',
    'venture.duplicate_bonus': '\n> <:bits:1411354539935666197> **+{amount} битсов** (бонус за дубликат)',
    'venture.resource_reward': '\n> {emoji} **+{amount} {type}**',
    'venture.interaction_ended': 'Взаимодействие завершено.',
    'venture.hint_revealed': 'Открыта буква: **{letter}**',
    'venture.super_hint_revealed': 'Супер подсказка: **{hint}**',
    'venture.guess_instruction': 'Угадайте имя пони на английском языке!',
    

    'validator.command_error': 'Что-то пошло не так. Попробуйте еще раз.',
    'validator.permission_error': 'Я не могу этого сделать! Мне нужно специальное разрешение, чтобы трогать эти шестеренки!',
    'validator.user_input_error': 'Это не выглядит правильно с моей стоматологической точки зрения! Не могли бы вы проверить еще раз?',
    'validator.missing_args': 'Мне нужно больше информации, чтобы помочь с вашими зубами... то есть, с вашим запросом!',
    'validator.api_error': 'Временной поток нарушен! Я не могу подключиться к необходимым измерениям прямо сейчас!',
    'validator.database_error': 'Мои стоматологические записи перепутались! Дайте мне минутку, чтобы реорганизоваться!',
    'validator.cooldown_error': 'Ого! Моим карманным часам нужно остыть, прежде чем мы снова это сделаем!',
    'validator.user_not_found': 'О боже! Я не могу найти этого пони на этом сервере!',
    'validator.cannot_moderate': 'Я не могу модерировать этого пони! Их роль выше моей или у них есть специальные разрешения!',
    'validator.self_moderate': 'О боже! Вы не можете модерировать себя! Это было бы как если бы я пыталась починить свои собственные зубы!',
    'validator.bot_moderate': '*хихикает* Я не могу модерировать себя, глупенький! Кто бы тогда помогал с записями к стоматологу?',
    'validator.not_timed_out': 'Этот пони не в тайм-ауте! Их зубы уже свободно болтают!',
    'validator.already_banned': 'Этот пони уже заблокирован на сервере! Их зубы давно исчезли!',
    'validator.not_original_user': 'О боже! Ваши копыта недостойны регулировки этих деликатных шестеренок! Только пони, который это начал, может трогать эти элементы управления!',
    'validator.nsfw_content': 'О боже! *краснеет* Я могу показать такие изображения только в NSFW каналах! Моя стоматологическая этика не позволяет иначе!',
    'validator.nsfw_channel_required': 'О боже! *краснеет* Эту команду можно использовать только в NSFW каналах! Моя стоматологическая этика не позволяет иначе!',
    

    'setup.welcome': 'Я рада помочь вам настроить ваш сервер для успеха! Как эксперт по управлению временем, я знаю, как важно иметь все правильно организованное. Позвольте мне помочь сделать ваш сервер безопасным и аккуратным!',
    'setup.everyone_checks_title': 'Проверка разрешений упоминания всех/здесь',
    'setup.everyone_checks_description': 'Я проверю, есть ли у каких-либо ролей разрешение упоминать всех или здесь, что может быть разрушительным для больших серверов.',
    'setup.everyone_checks_loading': 'Проверяю разрешения упоминания для всех ролей... это может занять момент!',
    'setup.everyone_checks_success': 'Я успешно проверила все роли на разрешения упоминания!',
    'setup.everyone_checks_no_issues': 'Отличные новости! Роли с рискованными разрешениями упоминания не найдены. Ваш сервер уже защищен от нежелательных массовых пингов!',
    'setup.everyone_checks_fixed': 'Я успешно удалила разрешение упоминания всех/здесь из проблемных ролей.',
    'setup.everyone_checks_cant_fix': 'У меня недостаточно разрешений, чтобы исправить эти роли. Пожалуйста, дайте мне разрешение \'Управление ролями\' и попробуйте снова.',
    'setup.permission_checks_title': 'Аудит разрешений ролей',
    'setup.permission_checks_description': 'Я проанализирую все роли и их разрешения, чтобы помочь вам выявить потенциальные риски безопасности.',
    'setup.permission_checks_loading': 'Анализирую разрешения ролей... это может занять момент!',
    'setup.permission_checks_success': 'Я успешно проверила все разрешения ролей!',
    'setup.permission_checks_safe': 'Эта роль имеет соответствующие разрешения для своей цели.',
    'setup.permission_checks_summary': 'Вот краткое изложение ролей и разрешений вашего сервера:',
    

    'time.days': 'day',
    'time.days_plural': 'days',
    'time.hours': 'hour',
    'time.hours_plural': 'hours',
    'time.minutes': 'minute',
    'time.minutes_plural': 'minutes',
    'time.seconds': 'second',
    'time.seconds_plural': 'seconds',


    'response.greetings.1': 'Привет! Готовы к стоматологическому осмотру?',
    'response.greetings.2': 'Время зубастых улыбок! Как я могу помочь?',
    'response.greetings.3': 'Минуэтт к вашим услугам! Ваша дружелюбная пони времени здесь!',
    'response.greetings.4': 'Тик-так! Идеальное время для стоматологического приема!',
    'response.greetings.5': 'Привет! Мой график свободен для помощи вам сегодня!',
    'response.farewells.1': 'Время летит! Увидимся на следующем приеме!',
    'response.farewells.2': 'Не забывайте чистить зубы! Пока!',
    'response.farewells.3': 'Мне нужно бежать! Часы тикают, и у меня есть другие приемы!',
    'response.farewells.4': 'До встречи! Продолжайте улыбаться!',
    'response.farewells.5': 'Пока-пока! Помните, чистый зуб - счастливый зуб!',
    'response.confused.1': 'Хм, мое чувство времени покалывает, но я не уверена, что вы имеете в виду...',
    'response.confused.2': 'Это сложный вопрос для моей стоматологической экспертизы!',
    'response.confused.3': 'Мои карманные часы вращаются в замешательстве!',
    'response.confused.4': 'Мне может понадобиться проверить мои стоматологические карты для этого!',
    'response.confused.5': 'Не могли бы вы объяснить это еще раз? Мои копыта запутались во времени!',
    

    'help.title': 'Справка по командам',
    'help.description': 'Доступные команды: **{total}**\nВыберите категорию ниже:',
    'help.commands_count': '{count} команд',
    'help.category_utility': 'Утилиты',
    'help.category_economy': 'Экономика',
    'help.category_moderation': 'Модерация',
    'help.category_management': 'Управление',
    'help.buttons_not_for_you': 'Только пользователь команды может использовать эти кнопки!',
    'help.category_title': 'Команды {category}',
    'help.back_to_menu': 'Назад в меню',
    

    'rarity.BASIC': 'Базовые',
    'rarity.RARE': 'Редкие',
    'rarity.EPIC': 'Эпические',
    'rarity.MYTHIC': 'Мифические',
    'rarity.LEGEND': 'Легендарные',
    'rarity.CUSTOM': 'Кастомные',
    'rarity.SECRET': 'Секретные',
    'rarity.EVENT': 'Ивентовые',
    'rarity.UNIQUE': 'Уникальные',
    'rarity.EXCLUSIVE': 'Эксклюзивные'
  }
};


export const t = async (key, guildId = null, placeholders = {}) => {
  try {
    let language = 'en';
    
    if (guildId) {
      language = await getGuildLanguage(guildId);
    }
    

    const translation = translations[language]?.[key] || translations['en'][key] || key;
    

    let result = translation;
    for (const [placeholder, value] of Object.entries(placeholders)) {
      result = result.replace(new RegExp(`{${placeholder}}`, 'g'), value);
    }
    
    return result;
  } catch (error) {
    console.error('Error getting translation:', error);
    return translations['en'][key] || key;
  }
};


export const ts = (key, language = 'en', placeholders = {}) => {
  try {
    const translation = translations[language]?.[key] || translations['en'][key] || key;
    

    let result = translation;
    for (const [placeholder, value] of Object.entries(placeholders)) {
      result = result.replace(new RegExp(`{${placeholder}}`, 'g'), value);
    }
    
    return result;
  } catch (error) {
    console.error('Error getting translation:', error);
    return translations['en'][key] || key;
  }
};

export default { translations, t, ts };